#!/bin/sh

uci -q batch <<-EOF
	set system.@system[0].hostname='iStoreOS'
	set system.@system[0].timezone='CST-8'
	set system.@system[0].zonename='Asia/Shanghai'

	delete system.ntp.server
	add_list system.ntp.server='ntp1.aliyun.com'
	add_list system.ntp.server='ntp.tencent.com'
	add_list system.ntp.server='ntp.ntsc.ac.cn'
	add_list system.ntp.server='time.apple.com'
EOF
uci commit system

# log level
uci set system.@system[0].conloglevel='1'
uci set system.@system[0].cronloglevel='9'
uci commit system

# zram
mem_total=$(grep MemTotal /proc/meminfo | awk '{print $2}')
zram_size=$(echo | awk "{print int($mem_total*0.25/1024)}")
uci set system.@system[0].zram_size_mb="$zram_size"
uci set system.@system[0].zram_comp_algo='lz4'
uci commit system


# 设置默认主题为argon
if [ "$VERSION_TYPE" != "minimal" ] && [ -z "$(uci -q get luci.main.pollinterval)" ]; then
    uci set luci.main.mediaurlbase='/luci-static/argon'
    uci set luci.main.pollinterval='3'
    uci commit luci
fi

# 默认wan口防火墙打开
uci set firewall.@zone[1].input='ACCEPT'
uci commit firewall

# packet steering
uci -q get network.globals.packet_steering > /dev/null || {
    uci set network.globals='globals'
    uci set network.globals.packet_steering=2
    uci set network.globals.steering_flows='128'
    uci commit network
}

# disable coremark
sed -i '/coremark/d' /etc/crontabs/root
crontab /etc/crontabs/root

# 设置默认主题为argon
uci set luci.main.mediaurlbase='/luci-static/argon'
uci commit luci

# opkg mirror
#if [ $(grep -c SNAPSHOT /etc/opkg/distfeeds.conf) -eq '0' ]; then
#    sed -i 's,downloads.openwrt.org,mirrors.aliyun.com/openwrt,g' /etc/opkg/distfeeds.conf
#else
#    sed -i 's,downloads.openwrt.org,mirror.sjtu.edu.cn/openwrt,g' /etc/opkg/distfeeds.conf
#fi

# zram
mem_total=$(grep MemTotal /proc/meminfo | awk '{print $2}')
zram_size=$(echo | awk "{print int($mem_total*0.25/1024)}")
uci set system.@system[0].zram_size_mb="$zram_size"
uci set system.@system[0].zram_comp_algo='zstd'
uci commit system

# 配置流量卸载
uci set firewall.@defaults[0].flow_offloading=1
uci commit firewall
/etc/init.d/firewall restart

# diagnostics
uci set luci.diag.dns='www.qq.com'
uci set luci.diag.ping='www.qq.com'
uci set luci.diag.route='www.qq.com'
uci commit luci

# 设置主机名映射，解决安卓原生TV首次连不上网的问题
uci add dhcp domain
uci set "dhcp.@domain[-1].name=time.android.com"
uci set "dhcp.@domain[-1].ip=203.107.6.88"
uci commit dhcp

# 设置所有网口可访问网页终端
uci delete ttyd.@ttyd[0].interface

# 设置所有网口可连接 SSH
uci set dropbear.@dropbear[0].Interface=''
uci commit

if [ "$( opkg list-installed 2>/dev/null| grep -c "^dnsmasq")" -ne '0' ];then
  uci set dhcp.@dnsmasq[0].cachesize='0'
  uci commit dhcp
  /etc/init.d/dnsmasq restart
fi

# extra packages
#echo "src/gz openwrt_core https://mirrors.cernet.edu.cn/openwrt/releases/24.10.2/targets/x86/64/packages" >> /etc/opkg/distfeeds.conf
#echo "src/gz openwrt_base https://mirrors.cernet.edu.cn/openwrt/releases/24.10.2/packages/x86_64/base" >> /etc/opkg/distfeeds.conf
#echo "src/gz openwrt_kmods https://mirrors.cernet.edu.cn/openwrt/releases/24.10.2/targets/x86/64/kmods/6.6.93-1-1745ebad77278f5cdc8330d17a3f43d6" >> /etc/opkg/distfeeds.conf
#echo "src/gz openwrt_luci https://mirrors.cernet.edu.cn/openwrt/releases/24.10.2/packages/x86_64/luci" >> /etc/opkg/distfeeds.conf
#echo "src/gz openwrt_packages https://mirrors.cernet.edu.cn/openwrt/releases/24.10.2/packages/x86_64/packages" >> /etc/opkg/distfeeds.conf
#echo "src/gz openwrt_routing https://mirrors.cernet.edu.cn/openwrt/releases/24.10.2/packages/x86_64/routing" >> /etc/opkg/distfeeds.conf
#echo "src/gz openwrt_telephony https://mirrors.cernet.edu.cn/openwrt/releases/24.10.2/packages/x86_64/telephony" >> /etc/opkg/distfeeds.conf
#echo "src/gz openwrt_extras https://mirrors.cqupt.edu.cn/openwrt/releases/24.10.2/x86_64" >> /etc/opkg/distfeeds.conf

# extra packages
# echo "src/gz openwrt_extras https://mirrors.cqupt.edu.cn/openwrt/releases/24.10.2/$(. /etc/openwrt_release ; echo $DISTRIB_ARCH)" >> /etc/opkg/distfeeds.conf

# docker mirror
if [ -f /etc/config/dockerd ] && [ $(grep -c daocloud.io /etc/config/dockerd) -eq '0' ]; then
    uci add_list dockerd.globals.registry_mirrors="https://docker.m.daocloud.io"
    uci commit dockerd
fi

exit 0
